using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generator;

/// <summary>
/// I feel like a caveman writing SignalBus template code so let's hope I can automate this!
/// </summary>
[Generator]
public class SignalBusGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var userSignalDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (syntaxNode, cancellationToken) => syntaxNode is ClassDeclarationSyntax,
                transform: (generatorSyntaxContext, cancellationToken) =>
                {
                    if (generatorSyntaxContext.Node is not ClassDeclarationSyntax classDeclarationSyntax)
                        return null; 
        
                    if (generatorSyntaxContext.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax,
                            cancellationToken) is not ITypeSymbol typedSymbol)
                        return null;

                    if (typedSymbol.IsAbstract)
                        return null;
                    
                    if (typedSymbol.BaseType is null)
                        return null;

                    if (typedSymbol.BaseType.Name != "UserSignalArgs"
                        && typedSymbol.BaseType.Name != "CancellableSignalArgs"
                        && typedSymbol.BaseType.Name != "HandledSignalArgs")
                        return null;
                    
                    return typedSymbol;
                }).Where(typedSymbol => typedSymbol is not null);

        
        context.RegisterSourceOutput(userSignalDeclarations, GenerateFiles);
    }

    private void GenerateFiles(SourceProductionContext context, ITypeSymbol? typedSymbol)
    {
        if (typedSymbol is null)
            return;
        
        var outputString = new StringBuilder();
        HashSet<string> namespaces = [];
        HashSet<string> parameters = [];
        namespaces.Add("System");
        namespaces.Add("Kolmetoista.Temperance.NCS");
        
        var symbolNameSpace = typedSymbol.ContainingNamespace.ToDisplayString();
        namespaces.Add(symbolNameSpace);
        var className = typedSymbol.Name;
        var properties = typedSymbol.GetMembers().ToList();
        var constructor = properties.Find(x => x.Name == ".ctor");
        var constructionParametersWithTypes = "";
        var constructionParameterNames = "";
        if (constructor is IMethodSymbol constructorSymbol)
        {
            foreach (var parameter in constructorSymbol.Parameters)
            {
                parameters.Add($"{parameter.Type.Name} {parameter.Name}");
                constructionParametersWithTypes += parameter.Type.Name;
                if (parameter.Type is INamedTypeSymbol namedType && namedType.IsGenericType)
                {
                    constructionParametersWithTypes += "<";
                    foreach (var argument in namedType.TypeArguments)
                    {
                        constructionParametersWithTypes += argument.Name + ", ";
                        namespaces.Add(argument.ContainingNamespace.ToDisplayString());
                    }
                    constructionParametersWithTypes = constructionParametersWithTypes.Substring(0, constructionParametersWithTypes.Length - 2);
                    constructionParametersWithTypes += ">";
                }
                constructionParametersWithTypes += " " + parameter.Name + ", ";
                constructionParameterNames += parameter.Name + ", ";
            }
        }

        foreach (var name in namespaces)
        {
            outputString.AppendLine($"using {name};");
        }
        
        outputString.AppendLine(@"
namespace Kolmetoista.Temperance.Signals;

#nullable enable
// <<auto-generated by the SignalBusGenerator.cs>>
public partial class SignalBus
{
");
        outputString.AppendLine($"    // Namespace: {symbolNameSpace}");
        outputString.AppendLine($"    // Classname: {className}");
        
        foreach (var typedInterface in typedSymbol.AllInterfaces)
            outputString.AppendLine($"    // Interface: {typedInterface}");
        
        if (typedSymbol.BaseType is not null)
            outputString.AppendLine($"    // BaseType: {typedSymbol.BaseType.Name}");
        
        foreach (var property in properties)
            outputString.AppendLine($"    // Property: {property.Name}");

        foreach (var parameter in parameters)
            outputString.AppendLine($"    // Construction Parameter: {parameter}");

        // finish creating the source to inject
        outputString.AppendLine($@"
    public delegate void {className}Handler({constructionParametersWithTypes}ref {className} args);
    public event {className}Handler? {className};
    public void Emit{className}({constructionParametersWithTypes}ref {className} args)");
        outputString.AppendLine(@"    {");
        outputString.AppendLine($"         {className}?.Invoke({constructionParameterNames}ref args);");
        outputString.AppendLine(@"    }
}");

        // inject the created source into the users compilation
        context.AddSource($"SignalBus.{className}.g.cs", SourceText.From(outputString.ToString(), Encoding.UTF8));
    }
}